studentName=input("enter student name")
print("Student name is:",studentName)
Tamil=int(input("enter the tamil mark"))
print("Tamil mark:",Tamil)
English=int(input("enter the english mark"))
print("English mark:",English)
Maths=float(input("enter the maths mark"))
print("Maths mark:",Maths)
science=int(input("enter the science mark"))
print("Science mark:",science)
social=float(input(" enter the social mark"))
print("social mark:",social)